"use client";

import { useState, useTransition } from "react";
import {
  generateAttendanceLog,
  generateMasteryPortfolio,
  generateProgressReport,
  generateTranscript,
} from "@/app/actions/homeschool-exports";
import type {
  AttendanceRecord,
  MasteryRecord,
  ProgressReportData,
  TranscriptEntry,
} from "@/app/actions/homeschool-exports";

export default function ExportRecords({
  studentId,
  studentName,
}: {
  studentId: string;
  studentName: string;
}) {
  const [isPending, startTransition] = useTransition();
  const [activeExport, setActiveExport] = useState<string | null>(null);
  const [month, setMonth] = useState(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  });

  function downloadHTML(filename: string, html: string) {
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function buildAttendanceHTML(records: AttendanceRecord[]) {
    const totalMinutes = records.reduce((a, r) => a + r.durationMinutes, 0);
    const rows = records
      .map(
        (r) => `<tr>
          <td style="padding:8px;border:1px solid #ddd">${r.date}</td>
          <td style="padding:8px;border:1px solid #ddd">${r.durationMinutes} min</td>
          <td style="padding:8px;border:1px solid #ddd">${r.coachName}</td>
          <td style="padding:8px;border:1px solid #ddd">${r.conceptsCovered.join(", ") || "General instruction"}</td>
        </tr>`,
      )
      .join("");

    return `<!DOCTYPE html><html><head><title>Attendance Log - ${studentName}</title>
      <style>body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px}
      table{width:100%;border-collapse:collapse;margin:20px 0}
      th{background:#f1f5f9;padding:10px;border:1px solid #ddd;text-align:left}
      @media print{body{margin:0}}</style></head>
      <body>
      <h1>Attendance Log</h1>
      <p><strong>Student:</strong> ${studentName}</p>
      <p><strong>Total Sessions:</strong> ${records.length} | <strong>Total Hours:</strong> ${(totalMinutes / 60).toFixed(1)}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      <table>
        <thead><tr><th>Date</th><th>Duration</th><th>Coach</th><th>Concepts Covered</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="margin-top:40px;font-size:12px;color:#666">Generated by MathPivot - mathpivot.com</p>
      </body></html>`;
  }

  function buildMasteryHTML(records: MasteryRecord[]) {
    const grouped = new Map<string, MasteryRecord[]>();
    for (const r of records) {
      const existing = grouped.get(r.unitTitle) || [];
      existing.push(r);
      grouped.set(r.unitTitle, existing);
    }

    const levelColors: Record<string, string> = {
      mastered: "#16a34a",
      proficient: "#2563eb",
      developing: "#d97706",
      introduced: "#9333ea",
      not_started: "#94a3b8",
    };

    let sections = "";
    for (const [unit, concepts] of grouped) {
      const rows = concepts
        .map(
          (c) => `<tr>
            <td style="padding:6px 8px;border:1px solid #e2e8f0">${c.conceptTitle}</td>
            <td style="padding:6px 8px;border:1px solid #e2e8f0;color:${levelColors[c.masteryLevel] || "#666"};font-weight:600">${c.masteryLevel}</td>
            <td style="padding:6px 8px;border:1px solid #e2e8f0">${c.standardCode || ""}</td>
            <td style="padding:6px 8px;border:1px solid #e2e8f0">${c.assessedAt ? new Date(c.assessedAt).toLocaleDateString() : ""}</td>
          </tr>`,
        )
        .join("");
      sections += `<h3 style="margin-top:24px">${unit}</h3>
        <table style="width:100%;border-collapse:collapse">
        <thead><tr><th style="background:#f1f5f9;padding:8px;border:1px solid #e2e8f0;text-align:left">Concept</th>
        <th style="background:#f1f5f9;padding:8px;border:1px solid #e2e8f0;text-align:left">Mastery</th>
        <th style="background:#f1f5f9;padding:8px;border:1px solid #e2e8f0;text-align:left">Standard</th>
        <th style="background:#f1f5f9;padding:8px;border:1px solid #e2e8f0;text-align:left">Assessed</th></tr></thead>
        <tbody>${rows}</tbody></table>`;
    }

    const mastered = records.filter(
      (r) => r.masteryLevel === "mastered" || r.masteryLevel === "proficient",
    ).length;

    return `<!DOCTYPE html><html><head><title>Mastery Portfolio - ${studentName}</title>
      <style>body{font-family:sans-serif;max-width:900px;margin:40px auto;padding:0 20px}
      @media print{body{margin:0}}</style></head>
      <body>
      <h1>Mastery Portfolio</h1>
      <p><strong>Student:</strong> ${studentName}</p>
      <p><strong>Total Concepts:</strong> ${records.length} | <strong>Mastered/Proficient:</strong> ${mastered} (${records.length > 0 ? Math.round((mastered / records.length) * 100) : 0}%)</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      ${sections}
      <p style="margin-top:40px;font-size:12px;color:#666">Generated by MathPivot - mathpivot.com</p>
      </body></html>`;
  }

  function buildProgressHTML(data: ProgressReportData) {
    return `<!DOCTYPE html><html><head><title>Progress Report - ${data.studentName}</title>
      <style>body{font-family:sans-serif;max-width:700px;margin:40px auto;padding:0 20px}
      .stat{display:inline-block;background:#f1f5f9;padding:16px 24px;border-radius:8px;margin:6px;text-align:center}
      .stat-value{font-size:28px;font-weight:700;color:#1e293b}
      .stat-label{font-size:12px;color:#64748b;margin-top:4px}
      @media print{body{margin:0}}</style></head>
      <body>
      <h1>Monthly Progress Report</h1>
      <p><strong>Student:</strong> ${data.studentName}</p>
      <p><strong>Period:</strong> ${data.month}</p>
      ${data.gradeLevel ? `<p><strong>Grade Level:</strong> ${data.gradeLevel}</p>` : ""}
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      <div style="margin:24px 0">
        <div class="stat"><div class="stat-value">${data.totalSessions}</div><div class="stat-label">Sessions</div></div>
        <div class="stat"><div class="stat-value">${(data.totalMinutes / 60).toFixed(1)}</div><div class="stat-label">Hours</div></div>
        <div class="stat"><div class="stat-value">${data.conceptsMastered}</div><div class="stat-label">Concepts Mastered</div></div>
        <div class="stat"><div class="stat-value">${data.overallMastery}%</div><div class="stat-label">Overall Mastery</div></div>
      </div>
      <h2>Highlights</h2>
      <ul>${data.highlights.map((h) => `<li>${h}</li>`).join("")}</ul>
      <p style="margin-top:40px;font-size:12px;color:#666">Generated by MathPivot - mathpivot.com</p>
      </body></html>`;
  }

  function buildTranscriptHTML(entries: TranscriptEntry[]) {
    const rows = entries
      .map(
        (e) => `<tr>
          <td style="padding:8px;border:1px solid #ddd">${e.courseName}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">${e.creditHours}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center;font-weight:700">${e.grade}</td>
          <td style="padding:8px;border:1px solid #ddd;text-align:center">${e.conceptsMastered}/${e.conceptsTotal}</td>
          <td style="padding:8px;border:1px solid #ddd">${e.completedAt ? new Date(e.completedAt).toLocaleDateString() : "In Progress"}</td>
        </tr>`,
      )
      .join("");

    return `<!DOCTYPE html><html><head><title>Transcript - ${studentName}</title>
      <style>body{font-family:sans-serif;max-width:800px;margin:40px auto;padding:0 20px}
      table{width:100%;border-collapse:collapse;margin:20px 0}
      th{background:#f1f5f9;padding:10px;border:1px solid #ddd;text-align:left}
      @media print{body{margin:0}}</style></head>
      <body>
      <h1>Academic Transcript</h1>
      <p><strong>Student:</strong> ${studentName}</p>
      <p><strong>Institution:</strong> MathPivot Academic Coaching</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString()}</p>
      <table>
        <thead><tr><th>Course</th><th style="text-align:center">Credits</th><th style="text-align:center">Grade</th><th style="text-align:center">Concepts</th><th>Completed</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="margin-top:20px;font-size:11px;color:#666">Grade Scale: A (90%+), B (80-89%), C (70-79%), D (60-69%), IP (In Progress)</p>
      <p style="font-size:12px;color:#666">Generated by MathPivot - mathpivot.com</p>
      </body></html>`;
  }

  function handleExport(type: string) {
    setActiveExport(type);
    startTransition(async () => {
      try {
        if (type === "attendance") {
          const now = new Date();
          const startDate = new Date(now.getFullYear(), 0, 1).toISOString();
          const endDate = now.toISOString();
          const result = await generateAttendanceLog(
            studentId,
            startDate,
            endDate,
          );
          if (result.success && result.data) {
            downloadHTML(
              `attendance-${studentName.replace(/\s+/g, "-")}.html`,
              buildAttendanceHTML(result.data),
            );
          }
        } else if (type === "mastery") {
          const result = await generateMasteryPortfolio(studentId);
          if (result.success && result.data) {
            downloadHTML(
              `mastery-portfolio-${studentName.replace(/\s+/g, "-")}.html`,
              buildMasteryHTML(result.data),
            );
          }
        } else if (type === "progress") {
          const result = await generateProgressReport(studentId, month);
          if (result.success && result.data) {
            downloadHTML(
              `progress-${studentName.replace(/\s+/g, "-")}-${month}.html`,
              buildProgressHTML(result.data),
            );
          }
        } else if (type === "transcript") {
          const result = await generateTranscript(studentId);
          if (result.success && result.data) {
            downloadHTML(
              `transcript-${studentName.replace(/\s+/g, "-")}.html`,
              buildTranscriptHTML(result.data),
            );
          }
        }
      } finally {
        setActiveExport(null);
      }
    });
  }

  const exports = [
    {
      key: "attendance",
      title: "Attendance Log",
      desc: "Session dates, durations, and concepts covered (YTD)",
      icon: "M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z",
    },
    {
      key: "mastery",
      title: "Mastery Portfolio",
      desc: "All concepts with mastery levels and assessment dates",
      icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z",
    },
    {
      key: "progress",
      title: "Monthly Progress Report",
      desc: "Sessions, mastery gains, and highlights for a specific month",
      icon: "M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z",
    },
    {
      key: "transcript",
      title: "Academic Transcript",
      desc: "Course grades based on mastery percentages",
      icon: "M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z",
    },
  ];

  return (
    <div className="space-y-3">
      {exports.map((exp) => (
        <div key={exp.key} className="flex items-center gap-3">
          <div className="w-10 h-10 bg-slate-100 rounded-lg flex items-center justify-center flex-shrink-0">
            <svg
              className="w-5 h-5 text-slate-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={1.5}
                d={exp.icon}
              />
            </svg>
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-slate-900">{exp.title}</p>
            <p className="text-xs text-slate-500">{exp.desc}</p>
          </div>
          {exp.key === "progress" && (
            <input
              type="month"
              value={month}
              onChange={(e) => setMonth(e.target.value)}
              className="text-xs border border-slate-200 rounded px-2 py-1"
            />
          )}
          <button
            onClick={() => handleExport(exp.key)}
            disabled={isPending}
            className="px-3 py-1.5 bg-slate-900 text-white text-xs font-medium rounded-lg hover:bg-slate-800 disabled:opacity-50 transition-colors"
          >
            {isPending && activeExport === exp.key
              ? "Generating..."
              : "Download"}
          </button>
        </div>
      ))}
    </div>
  );
}
